//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieTable
    {
        public int Id { get; set; }
        public string movie_name { get; set; }
        public double ticket_price { get; set; }
    }
}
